#!/usr/bin/env python3
"""
Plot replication timeline events from LAMMPS output.

Reads:
- input.lammps (to get N_rec, n_replications, N_rouse_time, N_rest)
- replication_timeline.dat (event log generated by input.lammps)
"""

from __future__ import annotations

import argparse
import csv
import math
import re
from pathlib import Path

import matplotlib.pyplot as plt


VAR_RE = re.compile(r"^\s*variable\s+(\w+)\s+equal\s+(.+?)\s*$")


def _clean_expr(expr: str) -> str:
    expr = expr.strip()
    if (expr.startswith('"') and expr.endswith('"')) or (
        expr.startswith("'") and expr.endswith("'")
    ):
        expr = expr[1:-1]
    return expr.strip()


def _resolve_value(name: str, exprs: dict[str, str], cache: dict[str, float]) -> float:
    if name in cache:
        return cache[name]
    if name not in exprs:
        raise KeyError(f"Variable '{name}' not found in input file.")

    expr = _clean_expr(exprs[name])
    expr = expr.replace("^", "**")
    expr = re.sub(r"\$\{(\w+)\}", r"\1", expr)  # ${x} -> x
    expr = re.sub(r"\bv_(\w+)\b", r"\1", expr)  # v_x -> x

    # Resolve variable names recursively.
    tokens = set(re.findall(r"\b[A-Za-z_]\w*\b", expr))
    safe_funcs = {"floor": math.floor, "ceil": math.ceil, "sqrt": math.sqrt, "abs": abs}
    safe_consts = {"PI": math.pi}

    local_ctx: dict[str, float | object] = {}
    for tok in tokens:
        if tok in safe_funcs or tok in safe_consts:
            continue
        if tok in exprs:
            local_ctx[tok] = _resolve_value(tok, exprs, cache)

    local_ctx.update(safe_funcs)
    local_ctx.update(safe_consts)

    value = eval(expr, {"__builtins__": {}}, local_ctx)  # noqa: S307 - controlled context
    cache[name] = float(value)
    return cache[name]


def parse_lammps_variables(input_path: Path) -> dict[str, float]:
    exprs: dict[str, str] = {}
    with input_path.open("r", encoding="utf-8") as f:
        for line in f:
            m = VAR_RE.match(line)
            if not m:
                continue
            var_name, expr = m.group(1), m.group(2)
            exprs[var_name] = expr

    needed = ["N_rec", "n_replications", "N_rouse_time", "N_rest"]
    cache: dict[str, float] = {}
    out: dict[str, float] = {}
    for key in needed:
        out[key] = _resolve_value(key, exprs, cache)
    return out


def read_timeline(path: Path) -> list[tuple[int, str, int]]:
    events: list[tuple[int, str, int]] = []
    with path.open("r", encoding="utf-8") as f:
        reader = csv.reader(f)
        for row in reader:
            if len(row) != 3:
                continue
            if row[0].strip().lower() == "step":
                continue
            try:
                step = int(float(row[0].strip()))
                event = row[1].strip()
                cycle = int(float(row[2].strip()))
            except ValueError:
                continue
            events.append((step, event, cycle))
    return events


def build_theoretical_timeline(
    vars_info: dict[str, float], start_step: int = 0
) -> list[tuple[int, str, int]]:
    n_rec = int(vars_info["N_rec"])
    n_rest = int(vars_info["N_rest"])
    n_rep = int(vars_info["n_replications"])
    cycle_len = n_rest + n_rec

    out: list[tuple[int, str, int]] = []
    for cycle in range(n_rep):
        t0 = start_step + cycle * cycle_len
        out.append((t0, "replication_done", cycle))
        out.append((t0, "sustain_no_reactions_start", cycle))
        out.append((t0 + n_rest, "sustain_no_reactions_end", cycle))
    return out


def plot_biological_timeline(ax, events, panel_title):
    """
    Plot replication timeline as horizontal bars by biological phase:
    - DNA Replication (instantaneous marker, slightly higher)
    - Mitosis (sustain_no_reactions)
    - Cell Cycle (from end of mitosis to next replication_done)
    """
    colors = {
        "DNA Replication": "#1F6DA5",
        "Mitosis": "#FF7F0E",
        "Cell Cycle": "#19DF29",
    }

    y_base = 0
    y_height = 0.3  # base height for Mitosis and Cell Cycle
    dna_extra_height = 0.1  # extra height for DNA Replication

    # Sort events by step
    events = sorted(events, key=lambda x: x[0])
    cycles = sorted(set(c for _, _, c in events))

    # Track which labels have been added to the legend
    legend_labels = set()

    for i, cycle in enumerate(cycles):
        # Get steps for this cycle
        rep_step = next(s for s, e, c in events if e == "replication_done" and c == cycle)
        mito_start = next(s for s, e, c in events if e == "sustain_no_reactions_start" and c == cycle)
        mito_end = next(s for s, e, c in events if e == "sustain_no_reactions_end" and c == cycle)

        # Mitosis bar
        label = "Mitosis" if "Mitosis" not in legend_labels else None
        ax.barh(
            y_base,
            width=mito_end - mito_start,
            left=mito_start,
            height=y_height,
            color=colors["Mitosis"],
            alpha=0.7,
            label=label
        )
        legend_labels.add("Mitosis")

        # Cell Cycle bar (from mito_end to next replication_done)
        if i < len(cycles) - 1:
            next_rep = next(s for s, e, c in events if e == "replication_done" and c == cycles[i + 1])
        else:
            next_rep = rep_step + (mito_end - mito_start)  # extend a bit for last cycle
        label = "Cell Cycle" if "Cell Cycle" not in legend_labels else None
        ax.barh(
            y_base,
            width=next_rep - mito_end,
            left=mito_end,
            height=y_height,
            color=colors["Cell Cycle"],
            alpha=0.5,
            label=label
        )
        legend_labels.add("Cell Cycle")

        # DNA Replication marker (slightly taller)
        label = "DNA Replication" if "DNA Replication" not in legend_labels else None
        ax.barh(
            y_base,
            width=10000,  # thin marker
            left=rep_step,
            height=y_height + dna_extra_height,
            color=colors["DNA Replication"],
            label=label
        )
        legend_labels.add("DNA Replication")

    # Clean axes
    ax.set_yticks([])
    ax.set_ylabel("")
    ax.set_xlabel("Timestep")
    ax.set_title(panel_title)
    ax.grid(True, axis="x", alpha=0.3)
    ax.legend(loc="upper right")

def plot_timeline(
    post_events: list[tuple[int, str, int]], vars_info: dict[str, float], out_png: Path
) -> None:
    start_step = 0
    rep_steps = [s for s, e, _ in post_events if e == "replication_done"]
    if rep_steps:
        start_step = min(rep_steps)
    theo_events = build_theoretical_timeline(vars_info, start_step=start_step)

    fig, axes = plt.subplots(2, 1, figsize=(12, 8), sharex=True)
    plot_biological_timeline(axes[0], theo_events, "Theoretical timeline (from input variables)")

    if post_events:
        plot_biological_timeline(axes[1], post_events, "Post-sim timeline (from replication_timeline.dat)")
    else:
        axes[1].set_title("Post-sim timeline (no data)")
        axes[1].text(
            0.5,
            0.5,
            "No post-sim events found.",
            transform=axes[1].transAxes,
            ha="center",
            va="center",
        )
        axes[1].set_yticks([])
        axes[1].grid(True, axis="x", alpha=0.3)

    n_rec = int(vars_info["N_rec"])
    n_rep = int(vars_info["n_replications"])
    n_rouse = int(vars_info["N_rouse_time"])
    n_rest = int(vars_info["N_rest"])
    subtitle = (
        f"N_rec={n_rec} | n_replications={n_rep} | "
        f"N_rouse_time={n_rouse} | N_rest={n_rest}"
    )
    fig.suptitle("Replication Timeline Events\n" + subtitle)
    axes[1].set_xlabel("Timestep")
    fig.tight_layout()
    fig.savefig(out_png, dpi=180)
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser(description="Plot replication event timeline.")
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("input.lammps"),
        help="Path to input.lammps",
    )
    parser.add_argument(
        "--timeline",
        type=Path,
        default=Path("replication_timeline.dat"),
        help="Path to timeline file",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("replication_timeline.png"),
        help="Output PNG path",
    )
    args = parser.parse_args()

    if not args.input.exists():
        raise SystemExit(f"Input file not found: {args.input}")
    vars_info = parse_lammps_variables(args.input)
    events: list[tuple[int, str, int]] = []
    if args.timeline.exists():
        events = read_timeline(args.timeline)
    else:
        print(
            f"Timeline file not found: {args.timeline}\n"
            "Creating only the theoretical panel."
        )
    plot_timeline(events, vars_info, args.out)

    print(f"Saved timeline plot to: {args.out}")
    print(
        "Parameters: "
        f"N_rec={int(vars_info['N_rec'])}, "
        f"n_replications={int(vars_info['n_replications'])}, "
        f"N_rouse_time={int(vars_info['N_rouse_time'])}, "
        f"N_rest={int(vars_info['N_rest'])}"
    )


if __name__ == "__main__":
    main()
