#!/usr/bin/env python3
"""
Plot replication timeline events from LAMMPS output.

Reads:
- input.lammps (to get N_rec, n_replications, N_rouse_time, N_rest)
- replication_timeline.dat (event log generated by input.lammps)
"""

from __future__ import annotations

import argparse
import csv
import math
import re
from pathlib import Path

import matplotlib.pyplot as plt


VAR_RE = re.compile(r"^\s*variable\s+(\w+)\s+equal\s+(.+?)\s*$")


def _clean_expr(expr: str) -> str:
    expr = expr.strip()
    if (expr.startswith('"') and expr.endswith('"')) or (
        expr.startswith("'") and expr.endswith("'")
    ):
        expr = expr[1:-1]
    return expr.strip()


def _resolve_value(name: str, exprs: dict[str, str], cache: dict[str, float]) -> float:
    if name in cache:
        return cache[name]
    if name not in exprs:
        raise KeyError(f"Variable '{name}' not found in input file.")

    expr = _clean_expr(exprs[name])
    expr = expr.replace("^", "**")
    expr = re.sub(r"\$\{(\w+)\}", r"\1", expr)  # ${x} -> x
    expr = re.sub(r"\bv_(\w+)\b", r"\1", expr)  # v_x -> x

    # Resolve variable names recursively.
    tokens = set(re.findall(r"\b[A-Za-z_]\w*\b", expr))
    safe_funcs = {"floor": math.floor, "ceil": math.ceil, "sqrt": math.sqrt, "abs": abs}
    safe_consts = {"PI": math.pi}

    local_ctx: dict[str, float | object] = {}
    for tok in tokens:
        if tok in safe_funcs or tok in safe_consts:
            continue
        if tok in exprs:
            local_ctx[tok] = _resolve_value(tok, exprs, cache)

    local_ctx.update(safe_funcs)
    local_ctx.update(safe_consts)

    value = eval(expr, {"__builtins__": {}}, local_ctx)  # noqa: S307 - controlled context
    cache[name] = float(value)
    return cache[name]


def parse_lammps_variables(input_path: Path) -> dict[str, float]:
    exprs: dict[str, str] = {}
    with input_path.open("r", encoding="utf-8") as f:
        for line in f:
            m = VAR_RE.match(line)
            if not m:
                continue
            var_name, expr = m.group(1), m.group(2)
            exprs[var_name] = expr

    needed = ["N_rec", "n_replications", "N_rouse_time", "N_rest"]
    cache: dict[str, float] = {}
    out: dict[str, float] = {}
    for key in needed:
        out[key] = _resolve_value(key, exprs, cache)
    return out


def read_timeline(path: Path) -> list[tuple[int, str, int]]:
    events: list[tuple[int, str, int]] = []
    with path.open("r", encoding="utf-8") as f:
        reader = csv.reader(f)
        for row in reader:
            if len(row) != 3:
                continue
            if row[0].strip().lower() == "step":
                continue
            try:
                step = int(float(row[0].strip()))
                event = row[1].strip()
                cycle = int(float(row[2].strip()))
            except ValueError:
                continue
            events.append((step, event, cycle))
    return events


def build_theoretical_timeline(
    vars_info: dict[str, float], start_step: int = 0
) -> list[tuple[int, str, int]]:
    n_rec = int(vars_info["N_rec"])
    n_rest = int(vars_info["N_rest"])
    n_rep = int(vars_info["n_replications"])
    cycle_len = n_rest + n_rec

    out: list[tuple[int, str, int]] = []
    for cycle in range(n_rep):
        t0 = start_step + cycle * cycle_len
        out.append((t0, "replication_done", cycle))
        out.append((t0, "sustain_no_reactions_start", cycle))
        out.append((t0 + n_rest, "sustain_no_reactions_end", cycle))
    return out


def _scatter_events(ax: plt.Axes, events: list[tuple[int, str, int]], panel_title: str) -> None:
    event_order = [
        "replication_done",
        "sustain_no_reactions_start",
        "sustain_no_reactions_end",
    ]
    y_map = {name: i for i, name in enumerate(event_order)}

    colors = {
        "replication_done": "#1f77b4",
        "sustain_no_reactions_start": "#ff7f0e",
        "sustain_no_reactions_end": "#2ca02c",
    }

    for event_name in event_order:
        xs = [step for step, event, _ in events if event == event_name]
        ys = [y_map[event_name]] * len(xs)
        if xs:
            ax.scatter(xs, ys, s=34, label=event_name, color=colors[event_name])

    for step, event, cycle in events:
        if event == "replication_done":
            ax.text(step, y_map[event] + 0.08, f"c{cycle}", fontsize=7, alpha=0.8)

    ax.set_yticks(list(y_map.values()), list(y_map.keys()))
    ax.set_ylabel("Event")
    ax.grid(True, axis="x", alpha=0.3)
    ax.set_title(panel_title)
    ax.legend(loc="upper right")


def plot_timeline(
    post_events: list[tuple[int, str, int]], vars_info: dict[str, float], out_png: Path
) -> None:
    start_step = 0
    rep_steps = [s for s, e, _ in post_events if e == "replication_done"]
    if rep_steps:
        start_step = min(rep_steps)
    theo_events = build_theoretical_timeline(vars_info, start_step=start_step)

    fig, axes = plt.subplots(2, 1, figsize=(12, 8), sharex=True)
    _scatter_events(axes[0], theo_events, "Theoretical timeline (from input variables)")

    if post_events:
        _scatter_events(axes[1], post_events, "Post-sim timeline (from replication_timeline.dat)")
    else:
        axes[1].set_title("Post-sim timeline (no data)")
        axes[1].text(
            0.5,
            0.5,
            "No post-sim events found.",
            transform=axes[1].transAxes,
            ha="center",
            va="center",
        )
        axes[1].set_yticks([])
        axes[1].grid(True, axis="x", alpha=0.3)

    n_rec = int(vars_info["N_rec"])
    n_rep = int(vars_info["n_replications"])
    n_rouse = int(vars_info["N_rouse_time"])
    n_rest = int(vars_info["N_rest"])
    subtitle = (
        f"N_rec={n_rec} | n_replications={n_rep} | "
        f"N_rouse_time={n_rouse} | N_rest={n_rest}"
    )
    fig.suptitle("Replication Timeline Events\n" + subtitle)
    axes[1].set_xlabel("Timestep")
    fig.tight_layout()
    fig.savefig(out_png, dpi=180)
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser(description="Plot replication event timeline.")
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("input.lammps"),
        help="Path to input.lammps",
    )
    parser.add_argument(
        "--timeline",
        type=Path,
        default=Path("replication_timeline.dat"),
        help="Path to timeline file",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("replication_timeline.png"),
        help="Output PNG path",
    )
    args = parser.parse_args()

    if not args.input.exists():
        raise SystemExit(f"Input file not found: {args.input}")
    vars_info = parse_lammps_variables(args.input)
    events: list[tuple[int, str, int]] = []
    if args.timeline.exists():
        events = read_timeline(args.timeline)
    else:
        print(
            f"Timeline file not found: {args.timeline}\n"
            "Creating only the theoretical panel."
        )
    plot_timeline(events, vars_info, args.out)

    print(f"Saved timeline plot to: {args.out}")
    print(
        "Parameters: "
        f"N_rec={int(vars_info['N_rec'])}, "
        f"n_replications={int(vars_info['n_replications'])}, "
        f"N_rouse_time={int(vars_info['N_rouse_time'])}, "
        f"N_rest={int(vars_info['N_rest'])}"
    )


if __name__ == "__main__":
    main()
